package com.example.demo.enums;

public enum ChildNeeds {
    SANS_LACTOSE, SANS_GLUTEN, VEGETARIEN, SANS_NOIX, SANS_CRUSTACES, SANS_OEUF, SANS_SOJA, SANS_LAITAGE, SANS_POISSON, SANS_FRUITS_DE_MER, SANS_ARACHIDES
}